[AdaptiveUiCodelab] Use NavigationSuiteScaffold
android/codelab-android-compose pull request #455
Opened 2024-05-21 16:14 UTC by jdkoren

Note this component doesn't support a navigation drawer. Keeping `NavigationDrawerContent` composable for now in case we intend to implement support for showing the drawer again.

2024-05-21 19:23 UTC, alexvanyo requested changes
Keeping the navigation drawer content in the underlying project sounds good to me, but I feel like we should remove it from the codelab if we don't use it. Otherwise it just feels like a bug: "why is this composable here if it is never called?"

2024-05-21 19:23 UTC, alexvanyo commented on AdaptiveUiCodelab/gradle/libs.versions.toml
> +material3AdaptiveNavSuite = "1.0.0-alpha07"
Nit: we should update these to beta now

2024-05-22 16:15 UTC, jdkoren commented on AdaptiveUiCodelab/gradle/libs.versions.toml
> +material3AdaptiveNavSuite = "1.0.0-alpha07"
Done

2024-05-22 17:05 UTC, jdkoren commented
> Keeping the navigation drawer content in the underlying project sounds good to me, but I feel like we should remove it from the codelab if we don't use it. Otherwise it just feels like a bug: "why is this composable here if it is never called?"

Removed

2024-05-28 22:02 UTC, alexvanyo approved these changes
Removal looks good to me

2024-05-28 22:10 UTC, merged